name: Sample
on:
  pull_request: null
  push:
    branches:
    - master
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        egison: [ '4.1.2', '4.0.3', '3.10.3' ]
    name: Egison ${{ matrix.egison }} sample
    steps:
      - uses: actions/checkout@master
      - name: Setup Egison
        uses: ./
        with:
          egison-version: ${{ matrix.egison }}
      - run: egison --version
