name: Update if release new version
on:
  schedule:
  - cron:  '0 10 * * *'
  pull_request: null

jobs:
  build:
    name: Build new version commit
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set default version
      id: default
      run: echo "::set-output name=version::$(sed -e s/export\ const\ defaultVersion\ =\ //g src/default.ts | sed -e s/\;//g | sed -e s/\'//g)"

    - name: Set latest version
      id: latest
      run: echo "::set-output name=version::$(curl -s https://api.github.com/repos/egison/egison-package-builder/releases/latest | jq .name | sed -e s/\"//g)"

    - name: Update new version default.ts
      if: ${{ steps.latest.outputs.version != steps.default.outputs.version }}
      env:
        NEW_VERSION: ${{ steps.latest.outputs.version }}
      run: echo "export const defaultVersion = \"$NEW_VERSION\"" > src/default.ts

    - name: Create Pull Request
      if: ${{ steps.latest.outputs.version != steps.default.outputs.version }}
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Feat: update default egison version'
        title: Release new egison version ${{ steps.latest.outputs.version }}
        body: |
         - [x] update default version in src
         - [ ] add new version revision to src
         - [ ] build TypeScript
         - [ ] update documents (README, actions.yml)
         - [ ] update sample workflow
        labels: New Egison Version
        branch: egison-version-${{ steps.latest.outputs.version }}
        base: master
        branch-suffix: random
